### ISSUE TITLE
about the motivation of this paper

### ISSUE THREAD

**Issue by Sungden** [pikipity/Compact-Artificial-Neural-Network-SSVEP#1]
Dear author, I have a question about the motivation of your paper. You mentioned that "the calibration data size in this study is much smaller than that in [6] and [22]. Therefore, the recognition results of the Conv-CA and the Guney-DNN are much lower than the results presented in [6] and [22]."  But from the performance of TRCA and eTRCA presented in Figure 3, I thought you used 5 calibrations for training for the benchmark dataset. So I don't know what the calibration size is used for this comparison. 

Please correct me if my understanding is wrong. Thanks!

**Comment by pikipity** [comment]
Thank you very much for your question. [6] is related to Guney-DNN. [22] is related to Conv-CA. These studies use cross-subject data to train their models. Our study only uses the individual data to train the model. Compared with these studies, the calibration data size is much smaller.

**Comment by pikipity** [comment]
Thank you very much for your question. [6] is related to Guney-DNN. [22] is related to Conv-CA. These studies use cross-subject data to train their models. Our study only uses the individual data to train the model. Compared with these studies, the calibration data size is much smaller.
